name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller  # Install PyInstaller for packaging

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install Node.js dependencies
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    # Build the React frontend
    - name: Build frontend
      run: |
        cd frontend
        npm run build

    # Package the app into a single executable
    - name: Package app with PyInstaller
      run: |
        pyinstaller launcher.spec

    # Upload the packaged executable as an artifact
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: SquatsApp
        path: dist/SquatsApp
