name: Build Squats App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu for testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Defines an external action for checking out code

      - name: Set up Python
        uses: actions/setup-python@v3  # Defines an external action for setting up Python
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyinstaller  # Shell command to install dependencies

      - name: Run Unit Tests
        run: |
          pytest tests/test_squats.py  # Shell command to execute tests

  build:
    runs-on: windows-latest  # Use Windows for building the executable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Defines an external action for checking out code

      - name: Set up Python
        uses: actions/setup-python@v3  # Defines an external action for setting up Python
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller  # Shell command to install dependencies

      - name: Build executable
        run: |
          cd ${{ github.workspace }}
          pyinstaller --onefile --noconsole --icon=squat-icon.ico main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: squats-executable
          path: '**/dist/*.exe'
