name: Build and Test Squats App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint tkcalendar

      # Step 4: Check code quality
      - name: Run pylint
        run: pylint src/

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: python -m unittest discover -s tests
        continue-on-error: true  # Explicitly fail on test failures

  build:
    runs-on: windows-latest
    needs: test  # Ensure this job runs only if the 'test' job succeeds

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller tkcalendar

      # Step 4: Build executable
      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --icon=squat-icon.ico --name=squats main.py

      # Step 5: Verify build output
      - name: Verify build directory
        run: ls -R dist/

      # Step 6: Test executable startup
      - name: Test executable startup
        run: dist/squats.exe || echo "Executable failed to start."

      # Step 7: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: squats-executable
          path: '**/dist/*.exe'
