name: Build Squats App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest  # Use Ubuntu for testing, Windows for build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pyinstaller

      - name: Run Unit Tests
        run: |
          pytest test_squats.py

      - name: Build executable (Windows)
        runs-on: windows-latest  # Switch to Windows for the build
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v3
            with:
              python-version: 3.x

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pyinstaller

          - name: Build executable
            run: |
              pyinstaller --onefile --noconsole --icon=squat-icon.ico squats.py

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: squats-executable
              path: dist/squats.exe
