name: Build and Test Squats App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest  # Use Windows for both testing and building

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint pyinstaller

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: python -m unittest discover -s tests

      # Step 5: Check code quality
      - name: Run pylint
        run: pylint src/

      # Step 6: Build executable
      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --icon=squat-icon.ico --name=squats main.py

      # Step 7: Verify build output
      - name: Verify build directory
        run: ls -R dist/

      # Step 8: Test executable startup
      - name: Test executable startup
        run: dist/squats.exe || echo "Executable failed to start."

      # Step 9: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: squats-executable
          path: '**/dist/*.exe'
